### ISSUE TITLE
コメントを書けるようにする

### ISSUE THREAD

**Issue by YuseiIto** [dynasty-lang/dynasty-lang#18]
#17 をやるためにコメントの書き方を決めたい。

私としては　[CのANTLR実装](https://github.com/antlr/grammars-v4/blob/master/c/C.g4)　を参考にして　
```
/* Block comment like this */

```
と
 
```
// This form of simple line comment

```

でコメントできるようにするのがわかりやすいと思う。
他に案はありますか

**Comment by frodo821** [comment]
私的には複行コメントなし、単行コメントは `#` 始まりが慣れてるので好き

**Comment by YuseiIto** [comment]
そうかー私はデバッグしている時に雑にコメントアウトして開発できるので好きなんだけどな、block comment.

**Comment by frodo821** [comment]
うーん、悩ましいなぁ……。実装の手間的な問題はまぁ置いておくとしても、ブロックコメントをありがたく思ったことがないのよね

**Comment by frodo821** [comment]
@YuseiIto

```g4
COMMENT: '#' ~[\n\r]*;
```
単行コメントはこれでいい？ `//`にこだわりがあるならそれでもいい

**Comment by YuseiIto** [comment]
実装の手間的な問題を置いておくのはどうなん?笑　使う言語にするならそこ大事な気が :eyes:

あと、複業コメントはライセンスとかに役立つというのもあると思っている。

**Comment by YuseiIto** [comment]
単行コメントの記号に特にこだわりはないけど、複行コメントの記号次第かな...

これはまあcommitのコードに残ったらただのbad practiceなんだけど、自分でデバッグする時には　[これ](https://qiita.com/smicle/items/bdc11092e2130b8e2333)　を多用する(&& Dynastyでもブロックコメント入れるならしたい) ので、複行コメントの記号次第かな...と思っている。

**Comment by frodo821** [comment]
@YuseiIto うーん……、その目的ならコンパイル時評価のif文導入する方がよくない……？

**Comment by frodo821** [comment]
@YuseiIto 
とりあえずブロックコメントは仕様に入れることにします。
```
# 単行コメント
#-
複行コメント
-#
```
でどうですか？

**Comment by YuseiIto** [comment]
いいですね、それでいこう
