### ISSUE TITLE
<type_lit>非終端記号の定義

### ISSUE THREAD

**Issue by frodo821** [dynasty-lang/dynasty-lang#3]
#1 で言及した<type_decl>非終端記号の定義は以下のようにします。

```g4
type_decl: 'type' fqn '=' type_desc;
type_desc: fqn | type_lit;
```

\<fqn\>非終端記号は完全修飾識別子を表していて、`<ident>.<ident>`のような形式を想定しています。
<type_lit>非終端記号は、型のメンバなどのリテラル表記を表していますが、どのような記法にするべきでしょうか。

案1
```
type SomeType = {
  public a: int;
  b: str;
} extends SomeSuperType;
```

案2
```
type SomeType = object of SomeSuperType has {
  public a is int;
  b is str;
};
```

案3
```
type SomeType = record :: SomeSuperType {
  public a :: int;
  b :: str;
}
```

ほかの案があればコメントをしてください。

**Comment by YuseiIto** [comment]
案１が好きです。

案2, `is` というkeywordは少し分かりにくい気もします。
VBとかにあるような `as`　の方が自分的にはしっくりきますが、まあ自分が慣らされているだけのような気もします。
案3は、 `::` が果たす役割がシンプルに説明できない(見た目のためにあるみたいな感じに見える) ものになっているように思います。

**Comment by frodo821** [comment]
extendsがいまいち嫌いなんだよね。案2は英語として読み下せる形を意識した。ごめん、案3はHaskellにすごい引き寄せられたの……。

**Comment by frodo821** [comment]
私としては、案1と案3の中間くらいがいいなって

**Comment by YuseiIto** [comment]
なるほどね...

案4
```
type SomeType: SomeSuperType={
  public a: int;
  b: str;
}
```

とかどうかな? 基底クラスははC的な感じで書いて、残りは案1(というかtsだね)ベース。
Haskellは見たことがあるだけだから幸せさをよくわかってないんだけど、案3にしかないメリットとか美しさとかあれば教えて欲しい。

**Comment by YuseiIto** [comment]
CというかC++だね

**Comment by frodo821** [comment]
案4をちょっと変形して、こんな感じならどう？

案5
```plain
type SomeType = SomeSuperType {
  public a: int;
  b: str;
}
```

**Comment by YuseiIto** [comment]
あ、いいじゃん!  `SomeSuperType` に設定を追加しているっぽい感じがしていい見た目だと思う!

**Comment by frodo821** [comment]
じゃあこれで行こうと思います！
